# Generated by Django 3.2.6 on 2021-08-27 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('level', models.IntegerField(choices=[(1, 'Rookie'), (2, 'Medium'), (2, 'Expert')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('type', models.IntegerField(choices=[(1, 'Musical video'), (2, 'Movie'), (3, 'TV show'), (4, 'Other')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trees_trees',
            },
        ),
    ]
